context:
  version: "0.0.12"
  python_min: '3.13'

package:
  name: pixi-browse
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/41/71/ef7eb6852a87e636aa2a9ddc8c9f6c827f8958ae249ed4cbccd798153ee0/pixi_browse-${{ version }}.tar.gz
  sha256: 08b79c88ed931b50d04cde335eacb8e2196bd700514dc59ad821a419cc5bc717

build:
  number: 0
  noarch: python
  python:
    entry_points:
      - pixi-browse = pixi_browse.__main__:cli
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - textual >=8.0.2,<9
    - py-rattler >=0.23.1,<0.24
    - typer >=0.24.0,<0.25
    - pyyaml >=6.0.3,<7
tests:
  - python:
      imports:
        - pixi_browse
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - pixi-browse --help
      - pixi-browse --version

about:
  homepage: https://github.com/pavelzw/pixi-browse
  repository: https://github.com/pavelzw/pixi-browse
  documentation: https://github.com/pavelzw/pixi-browse
  summary: A TUI to browse conda packages
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
