context:
  version: "0.0.8"
  python_min: '3.13'

package:
  name: pixi-browse
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pixi-browse/pixi_browse-${{ version }}.tar.gz
  sha256: e10985a606dabb5bd55e0a310a470c3842a6c4fd9733d9fb6f3135cfb993ee5b

build:
  number: 0
  noarch: python
  python:
    entry_points:
      - pixi-browse = pixi_browse.__main__:cli
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - textual >=8.0.2,<9
    - py-rattler >=0.23.1,<0.24
    - typer >=0.24.0,<0.25
    - pyyaml >=6.0.3,<7
tests:
  - python:
      imports:
        - pixi_browse
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - pixi-browse --help
      - pixi-browse --version

about:
  homepage: https://github.com/pavelzw/pixi-browse
  repository: https://github.com/pavelzw/pixi-browse
  documentation: https://github.com/pavelzw/pixi-browse
  summary: A TUI to browse conda packages
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
